name: Deploy To SFTP

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NASA_API: ${{ secrets.NASA_API }}
        
      - name: Build Astro Website
        run: pnpm build

      - name: Sync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --progress
          path: dist/
          remote_path: /web/pages/limsezam.ovh
          remote_host: ${{ secrets.FTP_HOST }}
          remote_user: ${{ secrets.FTP_LOGIN }}
          remote_key: ${{ secrets.FTP_KEY }}


          
      - name: Clear Cloudflare cache
        env:
          ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache" \
            -H "Authorization: Bearer ${API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
